[package]
name = "hg-ctx2d"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.22.0", features = ["min_const_generics"] }
thunderdome = "0.6.1"
wgpu = { version = "24.0.1", default-features = false }
