[package]
name = "hg-client"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-where = "1.2.7"
hg-ecs = { version = "0.1.0", path = "../hg-ecs" }
hg-utils = { version = "0.1.0", path = "../hg-utils" }
macroquad = "0.4.13"
