[package]
name = "hg-common"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.27.0", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }

hg-engine-common.workspace = true
